### ISSUE TITLE
Cannot connect to server (while server seems running)

### ISSUE THREAD

**Issue by movabo** [inexorgame/inexor-core#574]
```
Feb 20 15:35:32 flex.instances.InstanceManager[5708] INFO:  Starting instance Default production server (id: 31414, type: server, port: 31414)
Feb 20 15:35:32 flex.instances.InstanceManager[5708] INFO:  Starting E:\Users\Moritz\Documents\My Games\Inexor\releases\0.9.8@alpha\bin\inexor-core-server.exe 31414
Feb 20 15:35:32 flex.instances.InstanceManager[5708] INFO:  server instance 31414 process started with PID 2092
Feb 20 15:35:32 flex.instances.InstanceManager[5708] INFO:  server instance 31414 changes state: stopped ---> started
Feb 20 15:35:32 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/tree/profiles/current -- 127.0.0.1 (127.0.0.1)
express deprecated req.param(name): Use req.params, req.body, or req.query instead ..\api\v1\InexorTreeRestAPI.js:75:20
Feb 20 15:35:32 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/dump -- 127.0.0.1 (127.0.0.1)
Feb 20 15:35:32 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances -- 127.0.0.1 (127.0.0.1)
Feb 20 15:35:33 core.server.31414[5708] ERROR: failed loading icon
Feb 20 15:35:33 core.server.31414[5708] INFO:  RPC server listening on 0.0.0.0:31414
Feb 20 15:35:33 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/dump -- 127.0.0.1 (127.0.0.1)
Feb 20 15:35:33 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31417/dump -- 127.0.0.1 (127.0.0.1)
Feb 20 15:35:38 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/connect -- 127.0.0.1 (127.0.0.1)
Feb 20 15:35:38 flex.instances.InstanceManager[5708] INFO:  Created a new GRPC connector
Feb 20 15:35:38 flex.instances.Connector.localhost.31414.c5ck[5708] WARN:  Node /instances/31414/server/serverbotlimit does not exist! Please fix this value in E:\Users\Moritz\Documents\My Games\Inexor\flex\node_modules\@inexorgame\inexor-flex\config\client\31414.toml
Feb 20 15:35:38 flex.instances.InstanceManager[5708] INFO:  server instance 31414 changes state: started ---> running
Feb 20 15:35:38 flex.gameserver.IntermissionService[5708] ERROR: Cannot read property 'intermission' of undefined
  err: TypeError: Cannot read property 'intermission' of undefined
      at IntermissionService.onInstanceConnected (E:\Users\Moritz\Documents\My Games\Inexor\flex\node_modules\@inexorgame\gameserver\IntermissionService.js:58:29)
      at emitOne (events.js:120:20)
      at Node.emit (events.js:210:7)
      at InstanceManager.transist (E:\Users\Moritz\Documents\My Games\Inexor\flex\node_modules\@inexorgame\instances\Instances.js:672:26)
      at connector.connect.then (E:\Users\Moritz\Documents\My Games\Inexor\flex\node_modules\@inexorgame\instances\Instances.js:452:26)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
Feb 20 15:35:38 core.server.31414[5708] INFO:  RPC Server: New client connected id 0
Feb 20 15:35:38 core.server.31414[5708] INFO:  dedicated server started, waiting for clients...
Feb 20 15:35:38 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/dump -- 127.0.0.1 (127.0.0.1)

# /connect localhost 31414
Feb 20 15:36:01 core.client.31417[5708] INFO:  attempting to connect to localhost:31414
Feb 20 15:36:01 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:36:04 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:36:07 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:36:10 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:36:10 core.client.31417[5708] ERROR: could not connect to server

# /connect 127.0.0.1 31414
Feb 20 15:39:27 core.client.31417[5708] INFO:  attempting to connect to 127.0.0.1:31414
Feb 20 15:39:28 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:39:31 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:39:34 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:39:37 core.client.31417[5708] INFO:  attempting to connect...
Feb 20 15:39:37 core.client.31417[5708] ERROR: could not connect to server
```

When looking at http://127.0.0.1:31416/api/v1/instances/31414/connect in the browser it returns an empty json and in the console appears:
```
Feb 20 15:40:58 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/tree/profiles/default -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/tree/profiles/current -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/tree/profiles/current -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/dump -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/client -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/server -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/serverfarm -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/devenv -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/devenv2 -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:07 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/profiles/remote -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:13 flex.server.FlexServer[5708] INFO:  [GET] /api/v1/instances/31414/connect -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:13 flex.instances.InstanceManager[5708] INFO:  Created a new GRPC connector
Feb 20 15:41:13 flex.instances.Connector.localhost.31414.y9zg[5708] WARN:  Node /instances/31414/server/serverbotlimit does not exist! Please fix this value in E:\Users\Moritz\Documents\My Games\Inexor\flex\node_modules\@inexorgame\inexor-flex\config\client\31414.toml
Feb 20 15:41:13 flex.instances.InstanceManager[5708] ERROR: Source state of server instance 31414 is not started
Feb 20 15:41:13 core.server.31414[5708] INFO:  E0220 15:41:13.295000000 11036 server_context.cc:163] assertion failed: !completion_op_
Feb 20 15:41:13 core.server.31414[5708] INFO:  RPC server stopped (0.0.0.0:31414)
Feb 20 15:41:13 flex.server.FlexServer[5708] INFO:  [GET] /favicon.ico -- 127.0.0.1 (127.0.0.1)
Feb 20 15:41:13 flex.server.FlexServer[5708] INFO:  [GET] /favicon.ico -- 127.0.0.1 (127.0.0.1)
```

The instance dump (http://127.0.0.1:31416/api/v1/instances/31414/dump) returns:
```
{"state":"running","type":"server","name":"Default production server","description":"Badly Configurated Servers Inc. proudly presents your first Inexor Server","port":"31414","versionRange":"0.x","channelSearch":"*","autostart":false,"autoconnect":false,"autorestart":false,"initialized":true,"version":"0.9.8","channel":"alpha","console":{"logger":null,"buffer":null},"pid":2092,"process":null,"connector":null,"dbgalias":4,"server":{"lockmaprotation":0,"restrictdemos":1,"restrictpausegame":0,"restrictgamespeed":1,"restrictpersistteams":0,"serverdesc":"Inexor Server Simulation","servermotd":"","spectatemodifiedmap":1,"modifiedmapspectator":1,"maxclients":12,"maxdupclients":0,"serverpass":"","adminpass":"","publicserver":0,"maxdemos":5,"maxdemosize":16,"extinfoip":0,"ctftkpenalty":1,"serveruprate":0,"serverip":"","serverport":31415,"aiman":{"botlimit":8,"serverbotbalance":1}},"textures":{"medieval_soc":{},"nothing":{"walls":{"sandy":{}}},"Q009":{},"sheik":{},"tech1soc":{},"tomek":{},"a_teammate":{},"evillair":{"dsi":{},"ex":{"ex512":{}}},"inexor":{"material":{"lava":{},"water":{}}},"nobiax":{"patterns":{}},"philipk":{"asianwad":{},"blazurban_2":{},"herrgard":{},"mistral":{},"pk01":{},"pk02":{},"random":{},"submerged":{},"swars":{},"witheredwad":{"barrel":{}}},"windastella":{}},"maps":{}}
```

All this happened on an unmodified fresh installation on Windows 10 with the windows-installer.

**Comment by a-teammate** [comment]
I think you are mistaken the port of flex with the gameserver port.
Just leave the port away when connecting.
but I agree having something like "port" in the config, without any further details WHICH port it is is confusing.

**Comment by IAmNotHanni** [comment]
@movabo You have to start the server via Inexor flex web interface before you can connect to it:

To start a server in Inexor flex, go to "instances" and click "start":

![error: could not find image!](https://raw.githubusercontent.com/inexorgame/visualisations/e475eb76f10a16a8d594ee5ad863bee335ac9ccc/wiki/Inexor_FLEX_start_default_production_server.jpg)

Then click "connect":

![error: could not find image!](https://raw.githubusercontent.com/inexorgame/visualisations/e475eb76f10a16a8d594ee5ad863bee335ac9ccc/wiki/Inexor_FLEX_connect_to_default_production_server.jpg)

**Comment by movabo** [comment]
Without the same error appears:

```
# /connect localhost
Feb 20 21:55:01 core.client.31417[10452] INFO:  attempting to connect to localhost:31415
Feb 20 21:55:03 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:06 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:09 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:12 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:12 core.client.31417[10452] ERROR: could not connect to server

# /connect 127.0.0.1
Feb 20 21:55:18 core.client.31417[10452] INFO:  attempting to connect to 127.0.0.1:31415
Feb 20 21:55:18 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:22 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:24 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:56 core.client.31417[10452] INFO:  attempting to connect...
Feb 20 21:55:56 core.client.31417[10452] ERROR: could not connect to server
```

**Comment by movabo** [comment]
@IAmNotHanni That's exactly the procedure i followed all the times.

**Comment by IAmNotHanni** [comment]
Try `/map cartel`.

**Comment by movabo** [comment]
```
Feb 20 22:17:46 core.client.31417[8872] INFO:  attempting to connect over LAN
Feb 20 22:17:49 core.client.31417[8872] INFO:  attempting to connect...
Feb 20 22:17:52 core.client.31417[8872] INFO:  attempting to connect...
Feb 20 22:17:55 core.client.31417[8872] INFO:  attempting to connect...
Feb 20 22:17:58 core.client.31417[8872] INFO:  attempting to connect...
Feb 20 22:17:58 core.client.31417[8872] ERROR: could not connect to server
```

**Comment by IAmNotHanni** [comment]
Make sure to click "connect" in inexor flex web UI before trying to load a map.

**Comment by movabo** [comment]
Aha, okay. That did it. But that's still way too complicated!

**Comment by IAmNotHanni** [comment]
> Aha, okay. That did it. But that's still way too complicated!
Yes that's why we need to fix it :)

**Comment by IAmNotHanni** [comment]
Fixed by https://github.com/inexorgame/inexor-flex/pull/26.
